### ISSUE TITLE
Port to GTK+ 3

### ISSUE THREAD

**Issue by yashagrawal3** [sugarlabs/fortune-maker-activity#1]

**Comment by yashagrawal3** [comment]
https://github.com/FOSSRIT/fortunehunter , cloned and tested both these activities and was unable to find any significant difference. @quozl what should be done?

**Comment by quozl** [comment]
Thanks.  Yet another hostile fork.

But examine the differences more closely, using a recursive diff.  For instance there is a license change for Sugar Labs, which is surprising as (a) Sugar Labs doesn't need a commercial license as far as I know, and (b) the existing license is likely enough.

Just now, https://github.com/sugarlabs/fortunehunter has been forked from https://github.com/FOSSRIT/fortunehunter so you can do the port there and we can suggest it to the FOSSRIT crew.

Keep in mind that the upstream repository and new fork contain two activities, not one.  That's not unusual, we have other examples of that, like the Wikipedia activity.
